# Lesson plan <span class="badge badge-draft1">✎ Very rough draft</span>

If delivered as a semester-long course, we suggest the following lesson plan. 

## Week 1

In class

- Slides in [keynote](https://github.com/ianhussey/improving-your-statistical-inferences-through-monte-carlo-simulations/raw/main/slides/week1/simulation_week_1.key), [powerpoint](https://github.com/ianhussey/improving-your-statistical-inferences-through-monte-carlo-simulations/raw/main/slides/week1/simulation_week_1.pptx), or [pdf](https://github.com/ianhussey/improving-your-statistical-inferences-through-monte-carlo-simulations/raw/main/slides/week1/simulation_week_1.pdf).

After class

- [Chapter 1: Required skills](../chapters/1_required_skills.qmd) and its exercises.
- [Chapter 2: Foundation concepts](../chapters/2_foundation_concepts.qmd).

## Week 2

In class

- [Chapter 3: Writing functions](../chapters/3_writing_functions.qmd).

After class

- Chapter 3's exercises (linked in chapter).

## Week 3

In class

- [Slides: Is this normally distributed?](https://github.com/ianhussey/improving-your-statistical-inferences-through-monte-carlo-simulations/blob/main/slides/week3/is_this_normally_distributed.html).
- [Chapter 4: Data Generating Process functions](../chapters/4_data_generating_process_functions.qmd).

After class

- Chapter 4's exercises (linked in chapter).
- [Chapter 5: Pseudo-random number generators](../chapters/5_pseudo_random_number_generators.qmd).

## Week 4

In class

- [Chapter 6: Analysis functions](../chapters/5_analysis_functions.qmd).
- [Chapter 11: Everything is regression](../chapters/11_everything_is_regression.qmd).

After class

- Chapter 5's exercises (linked in chapter).

## Week 5

In class

- [Chapter 7: Creating simulation experiments](../chapters/6_creating_simulation_experiments.qmd). 

After class

- Chapter 7's exercises (linked in chapter).

## Week 6

In class

- [Chapter 8: Mapping functions](../chapters/7_mapping.qmd). 

After class

- Chapter 8's exercises (linked in chapter).

## Week 7

In class

- More discussion of [Chapter 8: Mapping functions](../chapters/7_mapping.qmd) specifically map() and unnest().
- [Chapter 12: Estimation](../chapters/12_estimation.qmd). 

After class

- Chapter 12's exercises (linked in chapter).

## Week 8

In class

- [Chapter 13: Hypothesis Testing](../chapters/13_hypothesis_testing.qmd).

After class

- Read [Lakens et al. (2018) "Equivalence Testing for Psychological Research: A Tutorial"](https://doi.org/10.1177/2515245918770963).
- Chapter 13's exercises (linked in chapter).

## Week 9

In class

- XX

After class

- XX

## Week 10

In class

- XX

After class

- XX

## Week 11

In class

- XX

After class

- XX

## Week 12

In class

- XX

After class

- XX

## Week 13

In class

- XX

After class

- XX

## Week 14

In class

- XX

After class

- XX

## Notes to self on structure

- [Chapter 8: Summarizing results](../chapters/8_summarizing_results.qmd).
- [Chapter 10: Summarizing results](../chapters/10_simulation_template.qmd).
chapters/9_planning_and_reporting - come back to this after substantive chapter 1 - week 7?, Siepe paper, assessing performance (MC SE), etc. Diagnostics on already run simulations, go in and check specific iterations, run manually etc.

where to add some additional material on parallelisation and optimisation, eg dropping the nested datasets and using a helper function to use pmap() more directly and efficiently?

## Note to self: badges:

- badge 1 <span class="badge badge-draft1">✎ Very rough draft</span>
- badge 2 <span class="badge badge-draft2">✎ Rough draft</span>
- badge 3 <span class="badge badge-draft3">✎ Polishing</span>
- badge 4 <span class="badge badge-complete">✓ Complete</span>


